- name: Set configure dns
  win_dns_client:
    adapter_names: '*'
    ipv4_addresses:
    - 192.168.200.10
    log_path: C:\dns_log.txt

- name: Verify File Server Role is installed.
  win_feature:
    name: File-Services, FS-FileServer
    state: present
    include_management_tools: True

- name: Install IIS Web-Server with sub features and management tools
  win_feature:
    name: Web-Server
    state: present
    include_sub_features: yes
    include_management_tools: yes
  register: win_feature

- name: reboot if installing web server feature requires it
  win_reboot:
  when: win_feature.reboot_required

- name: Ensure directory structure for public share exists
  win_file:
    path: C:\shares\public
    state: directory

- name: Ensure public share exists
  win_share:
    name: public
    description: Basic RW share for all domain users
    path: C:\shares\public
    list: yes
    full: Administrators
    change: Users

- name: add member server to alebov.local
  win_domain_membership:
    dns_domain_name: alebov.local
    domain_admin_user: test_admin@alebov.local
    domain_admin_password: StrongPass123!
    state: domain
  register: domain_state

- name: reboot member server if needed
  win_reboot:
  when: domain_state.reboot_required
